all:
  vars:
    ansible_user: avuser
    ansible_ssh_private_key_file: ~/.ssh/robo
    ansible_python_interpreter: /usr/bin/python3
    
  children:
    bastion:
      hosts:
        bastion-host:
          ansible_host: 158.160.56.15
          
    workers:
      hosts:
        worker-1:
          ansible_host: 10.10.10.15
        worker-2:
          ansible_host: 10.10.20.5
        worker-3:
          ansible_host: 10.10.30.12
        worker-4:
          ansible_host: 10.10.10.10
        worker-5:
          ansible_host: 10.10.20.7
        worker-6:
          ansible_host: 10.10.30.15
        worker-7:
          ansible_host: 10.10.10.21
        worker-8:
          ansible_host: 10.10.20.13
      vars:
        ansible_ssh_common_args: '-o ProxyJump=avuser@158.160.56.15'  